
spring:
  application:
    name: job-service
  datasource:
    url: jdbc:mysql://localhost/comproJob
    username: ea
    password: cs544
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8003